language: go
go:
- master
install:
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
- go get github.com/jteeuwen/go-bindata/...
- go get github.com/elazarl/go-bindata-assetfs/...
- go get github.com/gorilla/websocket
- go get github.com/nicksnyder/go-i18n/i18n
- go get github.com/patrickalin/GoMyLog
- go get github.com/patrickalin/bloomsky-api-go
- go get github.com/spf13/viper
- go get .
script:
- go test -v -covermode=count -coverprofile=coverage.out
- echo $COVERALLS_TOKEN
- ls -la
- "$HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken
  $COVERALLS_TOKEN"
before_deploy:
- "./command/compile.sh"
- ls bin/goBloomsky-darwin-amd64.bin
deploy:
  provider: releases
  api_key:
    secure: vIq3WGL3RPhqE583zzrO1db73pmfkFtFfLbsHPtHFwLjNNxjjO3IOuS6TsJu3ZMYshseZkRj1B7fmsBAXjchNVwaKvz2pyX8euU/TFEP5tlIag1Uh5/guJvWI3mRdCE/AXjyIqAVzjyqnrFWIP5OQ65di7yelL3uAt6xo3/gESpfvrhrrOtH3ENBn0jnptFkCpJMMHHe1MptmBMgP87x5rJX1mIPHypLVp7Z4LOvA2IAzL34yN1sql2Td0zItSLGhAS+pViYdsSP6mgCi3vkiQxZ4oWBoUf/b8GN202FQofV78Fy/P3X9vmwp3g6MD8tj2xhXfQmVVDX1hpDOuC8PQpU0v23vTLgFgHRG6EQI/tPvqa+rgoTpGsLtSJpkv787VfVfMRTBUBVZJg6Of44cGPQj+JXCML3Iczfn7OyWd0goytvHXdjgNFkhoAPEDXQRheYDMh0nlFxwFv+S4M6N5ZgWh/81NdHl17eJ5g7cGwQzli0eABra2NriNBzPiARSewtl46aIZlQvMz2v6M7+G/HHI1vzablsnAC+DheWo9CXj5lWJzTau+JB75dp1swgBONZUloyl1jAmTBr6OVPAD2KxFVYzuvbYUQy3UvMxdibEl8ATWmM+2AZfBztYd96e0E7axwVMJq8Kw9rwSTkHQyhMJ+K4TpIgGNHaZFz4E=
  file_glob: true
  file:
  - bin/goBloomsky-darwin-386.bin
  - bin/goBloomsky-darwin-amd64.bin
  - bin/goBloomsky-linux-386.bin
  - bin/goBloomsky-linux-amd64.bin
  - bin/goBloomsky-windows-386.exe
  - bin/goBloomsky-windows-amd64.exe
  - config.yaml
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
after_success:
  - BRANCHES_TO_MERGE_REGEX='^devel' BRANCH_TO_MERGE_INTO=master GITHUB_REPO=patrickalin/bloomsky-client-go /command/mergeScript.sh
env:
  global:
  - secure: OnelAxGwR9hD1Qzl5/olfyWpIcFUdjn7UBpXEY5x6jRcThCb0DtSidBCQnRbESX89D9Sii7b2inh0/uhEWXqE+ZZG9Ld66bcWdnLb2GB48swZJ4c7LEZrCobIG7lE2u04nH+Iw09fdf93R/s28VeCDdGsiUGlFZxnPwxje1SCvyZvwJcNHvk8+9+tGl3ddvuvk5/+7mH2H/+Ai/xp4foTN73KqwIzphsJfcgpAfpJRnN6l5pmiwq8kqLVvbZJTjqJJNw5xcXen1jn5itUXSBxCjwpTjf6eAZIVlHND08R0vqRjDStzp+yx8/1mgT9XZPj+SXtagTLfvL665wZuL2iy0ALOa2NVN5++LLLx9SaXgBE2a7SH2CRZ5dKpCqhUFlUragwH3fk2vdgeBuZawAJ8OcTkL2LqyZals9JjAKYtT0cC7ZE3Ae5bxBUrbCc3MjDN1IfSqkzvQfhsisKh9A7I7IV+Q+5WhAmPRb/uxZ5Pt8oCw8Ju0szG0wSrkU/Z+a71HErt8ZCWYFC2xWlj4wUOXGFzzcPyBT/tCv6mjATq50nNZWkb/TraAeWMGXJ0nwRX+Z3qeewNduatSAAX52nU70tIEm0eKtKLGglqBvP0I44AMG5tSnDTygcPa26SWQ6n9JxSRYmbt7w7Y2ZOW+cvKyKA9XdyW5+GlGkqpCOvM=
  - secure: oxjj5JICegPhXpyJ9ajwWmqVL0qL6WClVp6Ep3EggG6rlHgM2+KnjuVEj2vs+gZ8k/f7Kso1wqbUkwtbDUJ+xbgJpyIvmRaJVCPx/SCbWKGkay1UBSwotsp88o2ieKqvQ/i4LWcoZ2nMxUeqH6Gqd2QBUESI4ZSAoUWd7LRcFXQzW6UYtG/EWUB++cau+PNi9baM2DLcjwBLCywJjRMJNFenI1T+/9Rgug1SopyJ08WjuLXylL/ZME10PHGWqozgQmJfzZql3Wt9xfde4k/R+rMpexkZZE/nkk7Dm/ilQqgIpYixS/UKPipfQ7fdoOGkMgrNNDXC/l7+twl5pXDDBrIqPYet94Hh70/eDDLx8NiJYOpSw99BH7VGSp9rwUP84vklxn8C3s+jDKxYXiHJGsQEaKUn9ibZpJLTpxfRbcOJibGVVyBbwCHM4p5TxtNNwhCDPdU0hY6PaPgp2gfk9lgry9h+5M6PphK75w7ejE4i9UcaZnKKVN3kLe44HqsCTMeBCjhqS6BKLuK2XC0uGkg5X4N450klArVScpfbte7rXKgvZ1mfQgq46NeppB8Hl8h7tmQBb9fsEx8GDbCQ1jG8Dl5lRW3zE7XNRQqSv4Iaw3e1UE2dRL41D17QAFlI/ROfrPzZxFI4dBR9Djow92nYreqapSblgXU0qY9mLm4=