---
# language (en-us, fr)
  language : en-us
######## Params for bloomsky
# Normally don't change
  bloomskyURL: "https://api.bloomsky.com/api/skydata/"
# the key, it's free : https://dashboard.bloomsky.com/
  bloomskyAccessToken: "yourtoken"
######## Refresh time, be not to small because you are blocked by openweather and bloomsky (in second)
  refreshTimer: "60"
######## If true display informations on console
  consoleActivated: true
######## If true display informations on webpage
  hTTPActivated: true
  hTTPPort : ":1111"
  hTTPSPort : ":1112"
######## Params influxDB necessary if true
  influxDBActivated: "false"
  influxDBServer: "localhost"
  influxDBServerPort: "8086"
  influxDBUsername: "root"
  influxDBPassword: "root"
  influxDBDatabase: "bloomsky"
######## Expert
# panic,fatal,error,warning,info,debug:
  logLevel: "debug"
# to use the code in offline mode put mock: true
  mock: true
# use template, static file in folder not in bundled
  dev: false
# use web socket secure by defaut use web socket non secure (necessary to put traefik front the webserver)
  wss: false
##########
